---
# WIFI
wifi_ssid: ' '
wifi_password: ''
ap_wifi_password: '        '

# Native API
api_password: ''

# RF Codes
rf_code_ventilation: '000000000000000000000000'
rf_code_attic_pc: '000000000000000000000000'
rf_code_printer: '000000000000000000000000'
rf_code_attic_desk_lamp: '000000000000000000000000'
rf_code_bedroom_tv: '000000000000000000000000'
rf_code_bedroom_back_wall: '000000000000000000000000'
rf_code_watch_tv: '000000000000000000000000'
rf_code_watch_media: '000000000000000000000000'
rf_code_listen_music: '000000000000000000000000'
rf_code_all_off: '000000000000000000000000'
